src = ../../queue/dequeue.c ../../queue/enqueue.c ../../queue/print.c ../DFS/addEdge.c ../DFS/createGraph.c ../DFS/newNode.c ../DFS/printGraph.c ./mainBfs.c ./BFS.c

compile: 
	gcc $(src) -o bfs.out

clean:
	rm *.o
